# Generated by Django 5.2.6 on 2025-09-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_fim',
            field=models.TimeField(default='09:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_inicio',
            field=models.TimeField(default='08:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.CharField(default='usuário padrão', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sala',
            name='capacidade',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(),
        ),
    ]
